[package]
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
edition = "2018"
name = "convert_encoding"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.26"
